### ISSUE TITLE
pd 0.49test3 printing annoying errors on console (macOS)

### ISSUE THREAD

**Issue by porres** [pure-data/pure-data#443]
this never happen, I have no idea

![screen shot 2018-09-11 at 13 33 50](https://user-images.githubusercontent.com/5360142/45374106-8936f600-b5c7-11e8-8e2f-ad4a65feabb1.png)

**Comment by Spacechild1** [comment]
I'm the culprit. does it print it all the time? what are your audio settings?

**Comment by porres** [comment]
Nothing, that's why it's weird...

**Comment by Spacechild1** [comment]
Ok, and with audio?

**Comment by danomatika** [comment]
I'm not seeing this with the current master. I start Pd, choose a USB sound interface for input & output, start the test tone patch, unplug, and Pd doesn't crash. No prints.

The only time I see any prints/hangs are when I try to re-select the device in the audio dialog but, of course, the portaudio device list is now stale. I'd suggest printing some sort of one-time error line that would at least suggest restarting Pd when this happens using Portaudio since it cannot handle dynamic hot plugging.

**Comment by porres** [comment]
I'm just using the default settings, with mac's bultin audio card, I never went into the audio settings, I don't know what's causing this. I'm just using Pd and suddenly this starts popping

**Comment by Spacechild1** [comment]
> since it cannot handle dynamic hot plugging.

well, on Windows it works. but since it seems to cause weirdness on OSX, I better make this fix Windows only for now and later (when I have more time and access to a Mac) apply it to OSX.

**Comment by umlaeute** [comment]
is this issue resolved with accepting #445

**Comment by Spacechild1** [comment]
waiting for Alex to confirm

**Comment by porres** [comment]
confirmed

**Comment by porres** [comment]
still happening with test3, so I changed the issue name, but it does occur much less

**Comment by porres** [comment]
I'm actually getting something else, time for a new report
