### ISSUE TITLE
Issue receiving large quantity of MIDI messages

### ISSUE THREAD

**Issue by mariobuoninfante** [pure-data/pure-data#554]
When Pd receives a large quantity of SysEx messages, the MIDI IN port 'gets stuck' and then you need to go to 'Media->MIDI settings...' and re-select the port, otherwise no MIDI messages will be received anymore.
Here's a video that shows the issue (pass: sysexissue):
https://vimeo.com/316624285
attached the Pd and Max patches used to repro.
This has been tested on a MacBookPro 2.7 GHz Intel Core i5 16 GB of ram using Pd 0.49-1
Similar results found on Windows 10 and Ubuntu Studio 16.04.

[Pd_SysEx_issue_repro.zip](https://github.com/pure-data/pure-data/files/2852774/Pd_SysEx_issue_repro.zip)

**Comment by mariobuoninfante** [comment]
this happens also with different MIDI messages, not only with SysEx

**Comment by mariobuoninfante** [comment]
Pd 0.47 can doesn't show the problem

**Comment by umlaeute** [comment]
could you also try Pd-0.48?

**Comment by umlaeute** [comment]
hmm, i cannot really reproduce this with a plain Pd-setup (see attached patches), using Pd-0.49-0 as shipped with Debian/buster (amd64), using the alsamidi backend.

at 2ms, i haven encountered *any* problems.

going down to 1ms, packages start getting dropped, but they keep getting in.


[sysex.zip](https://github.com/pure-data/pure-data/files/2855494/sysex.zip)

**Comment by Lucarda** [comment]
@umlaeute 

Using a "Virtual loopback MIDI cable" (https://www.tobias-erichsen.de/software/loopmidi.html) i can send using your "sender.pd" to http://www.midiox.com/ @ **1ms** with no problem.


![sysex](https://user-images.githubusercontent.com/25239522/52634055-ef8cb100-2ea4-11e9-978b-580a56a01dc0.png)




When using your "receiver.pd" I cant go faster than **8ms**. Then it hangs and I have to reset the midi-in driver as in @mariobuoninfante  video.

Win8.1
Pd 0.49.0 64bit.

**Comment by Spacechild1** [comment]
FWIW, I have recently encountered situations on Windows 7 where MIDI input would sometimes stop working. I wasn't sure about the cause of the problem and had no time to debug it. I *think* this happened after I switched from 0.48 to 0.49. I used a keyboard which sends a lot of realtime clock messages, so maybe it's the same issue which Mario is experiencing (but might as well be a problem with the MIDI interface).

**Comment by mariobuoninfante** [comment]
double checked Pd 0-.48.0 and that works fine. the issue is not there.
Tested on MacBookPro 2.7 GHz Intel Core i5 16 GB MacOS Sierra

**Comment by umlaeute** [comment]
iirc @danomatika fixed a few things in the portmidi implementation. that's the only occasion where i think the problem could have crept into the code (and it would explain why the linux builds are not affected)

**Comment by mariobuoninfante** [comment]
@umlaeute On Linux also there are 'bandwidth' issues. If you try to deal with the same amount of data, something would get lost for sure. Do you think that's due to ALSA?

**Comment by umlaeute** [comment]
well, as i said: i couldn't reproduce this on my linux machine (using a "virtual" midi connection between two Pd instances on the same machine.

**Comment by mariobuoninfante** [comment]
Yap, but you said messages got dropped. And I experienced the same in other occasion (receiving FW via SysEx from HW devices)

**Comment by umlaeute** [comment]
but this issue is about MIDI-IN "getting stuck" (?)

**Comment by mariobuoninfante** [comment]
fair enough ;)
I'll open another after doing some further testing

**Comment by mariobuoninfante** [comment]
also, if reading the title, here we're talking about dealing with large quantity of messages. Would it be ok to put here info about Linux performances?

**Comment by umlaeute** [comment]
sure.
i've been running my patch for >5minutes now, sending 21-byte SysEx messages (including the start and stop byte) at a rate of 2ms, without a single dropout.

after that i raised the message ength to 101 bytes, and let it run for another 5 minutes. still no dropout.

**Comment by mariobuoninfante** [comment]
Hi,
I just updated the title of this bug, as it's been proven that the issue is not only with SysEx but with all the MIDI msg.
is there any update on this? I'm simply curious to know what's the issue :)

**Comment by danomatika** [comment]
I've not had any time to look at it. It would be nice if there was more than one developer interested in MIDI...

**Comment by mariobuoninfante** [comment]
I totally understand. 
Unfortunately I'm not a C/C++ programmer, but I can try to have a look at it and see if I can spot anything. There area where to look seems to be clear anyway, since we've been able to track down when the issue has been introduced (0.48.1)

**Comment by Spacechild1** [comment]
I can reproduce this problem on Windows by "connecting" two Pd instances with a MIDI loopback (https://www.tobias-erichsen.de/software/loopmidi.html) and sending a simple MIDI message from one instance to the other at an interval of 1 ms. after about 2 seconds, the [midiin] object stops outputting anything (while the loop back program itself still shows traffic) and I have to reset the MIDI device in the MIDI settings. since @umlaeute can't reproduce this with alsamidi, it seems to be a problem with portmidi. note that this happens both with Pd 0.48 and Pd 0.49. I can have a look but not in the next few days I'm afraid...

**Comment by Spacechild1** [comment]
ok, I think I've fixed this in the PR above, the error was only in the Pd code.

@mariobuoninfante here are binaries containing the bugfix:
[pd-0.49.0-midi-fix.zip](https://github.com/pure-data/pure-data/files/3129316/pd-0.49.0-midi-fix.zip)

can you test and tell me if this fixes your problems?

**Comment by porres** [comment]
@Spacechild1 , you're on fire :)

**Comment by mariobuoninfante** [comment]
Hi @Spacechild1,

really sorry I've seen this just now, I'm getting the build and test it. Max tomorrow I'll get back to you.
sorry for the late reply

**Comment by mariobuoninfante** [comment]
@Spacechild1 ,
is the build you attached here, the same I can find here: https://github.com/pure-data/pure-data/issues/581?
cause I tried that one (so that I didn't have to compile anything) and it still gets stuck when I use the Max Patch attached above

**Comment by Spacechild1** [comment]
no, that's a totally different issue. use the one above ("pd-0.49.0-midi-fix.zip")

**Comment by mariobuoninfante** [comment]
> no, that's a totally different issue. use the one above ("pd-0.49.0-midi-fix.zip")

@Spacechild1 
I cannot find neither the MacOS App nor the autogen to build it. Am I missing something?

**Comment by Spacechild1** [comment]
oh, it's a Windows build. if you want to build from source for Mac, clone my branch: https://github.com/Spacechild1/pure-data/tree/midi-fix

**Comment by mariobuoninfante** [comment]
@Spacechild1 it's rock-solid!!!!!
21 bytes per msec, and it doesn't seem to drop a single byte, plus it never get stuck :)

**Comment by mariobuoninfante** [comment]
Hey guys,

I'm just curious why this has been reverted https://github.com/pure-data/pure-data/commit/7cbc5e41b8de537a545720f2f05c1d741709e41e
is there any particular reason?

**Comment by danomatika** [comment]
>is there any particular reason?

This change is in fact in the sources now. You are seeing my first quick fix which ended up being more involved.

I reverted as the response form the port midi developers was "wait, why would you NOT want it?" After some discussion and testing, we all decided it was needed and they will incorporate the define override upstream.

**Comment by Spacechild1** [comment]
Also, the commit in question is actually about *sending* MIDI. The PR about *receiving* MIDI is still open: https://github.com/pure-data/pure-data/pull/598

**Comment by mariobuoninfante** [comment]
ok, it makes sense of course
thanks @danomatika @Spacechild1  :)
