### ISSUE TITLE
key repeat set to off is still repeating

### ISSUE THREAD

**Issue by sevdh** [pure-data/pure-data#729]
I know a lot of work has gone into key, keyup and keyname issues: https://github.com/pure-data/pure-data/issues/213
I'm on macos 10.14.16 with pd-0.50-0-test1 and I still have one issue. The 'Key Repeat' and 'Delay Until Repeat' from the system preferences are working well except for setting 'Key Repeat' to off. When set to off the pressed key still keeps on repeating.
Best!
Edwin

**Comment by sevdh** [comment]
I'm sorry I was testing keyboard repeat more and it is macOS itself that still repeats when the slider in the system preferences is set to off(!)
Afterwards I tried to set ApplePressAndHoldEnabled to True for Pd with the following command in the terminal: 'defaults write org.puredata.pd.pd-gui ApplePressAndHoldEnabled -bool true'
This does change the setting temporarily but is without success since Pd is actively setting ApplePressAndHoldEnabled to false at startup.
'defaults read org.puredata.pd.pd-gui' gives this after launching Pd:
{
    ApplePressAndHoldEnabled = 0;
    NSNavLastRootDirectory =   .....
    ........
}
I'm sure there is a good reason why it is set to false but nevertheless: how would Pd behave if ApplePressAndHoldEnabled is set to 1? Are there other things in the GUI that break or are not favorable?

**Comment by danomatika** [comment]
>how would Pd behave if ApplePressAndHoldEnabled is set to 1

Any accent keys would not repeat as the accent composer is launched, although you never see it.

You can disable setting the by commenting line 149 in pd_guiprefs.tcl inside your Pd app bundle:

1. right-click on Pd .app and choose "Show contents" (or translation)
2. file is in Contents/Resources/tcl, edit and save
3. restart Pd

**Comment by danomatika** [comment]
To note: I am not likely to fix this as I wasn't able to find a solution the last time. I figure having [keyup] and key repeat work at all was good enough.

**Comment by sevdh** [comment]
Thanks! Yes, I can set ApplePressAndHoldEnabled to 1 now. However it doesn't seem to change anything in Pd's behavior (not even for the keys that should open the accent composer). All keys are still repeating.
I understand you can't (easily) fix this because it is actually macOS that doesn't properly switch off the key repeat although the system preferences indicate the possibility.

**Comment by porres** [comment]
Hey, I opened a similar issue here https://github.com/pure-data/pure-data/issues/818

So, I'm using pd 0.50-2 , macOS 10.14.6 and I've been using [keyname] to program buttons so things happen when I press a certain key. I thought it was working fine, because if I kept the key pressed I'd see "1" and "0" only showed up when I released the key. But now I see it keeps changing from 0 to 1 quite fast. The [keyup] object also sends the key number before I release it.

One thing I found funny is that I see this kind of thing where the pressed key gets repeated only happens in Pd and not other software.
 
So I found this issue here and saw about the system preferences, which hadn't ocurred to me (since other software were not repeating keys). Anyway, I turned repetition off and now it all works fine in Pd!!!!!!!!

**Comment by danomatika** [comment]
I think IOhannes work to fix key ha sling in 0.50 fixed this as well as my Tk patch which added checking for the system preference.

Can the original author of this issue test with the latest Pd release version to confirm the issue or that it is now fixed? If so, please close this.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by sevdh** [comment]
On macOS 10.14.6 and Pd-0.50-2 I still get repeating keys even if Key Repeat is set to Off in the system preferences.

I’ve just checked this on Pd-0.50.2-double-test1 and it gives the same behaviour.

The reason I’m interested in this working correctly is that it would allow to use the computer keyboard as a keyboard as a ‘piano keyboard’ and hold keys as long as you want.

All the best!

Edwin

**Comment by porres** [comment]
you know, for me it didn't work at first when I changed it, so I had to close and reopen Pd, then it worked - we got the exact same system configuration, please try again?

**Comment by sevdh** [comment]
You are absolutely right! I didn’t test this with quitting Pd in between.

I’m very happy that this does work!

Cheers!

**Comment by sevdh** [comment]
I'm closing this issue

**Comment by porres** [comment]
> So I found this issue here and saw about the system preferences, which hadn't ocurred to me (since other software were not repeating keys). Anyway, I turned repetition off and now it all works fine in Pd!!!!!!!!

I'm just thinking what if I want Pd to ignore if system preferences enables autorepeat? Like, what if I don't want it to repeat keys even though I didn't set it under system preferences? Moreover, what if I want to guarantee that my patch/abstraction will work as intended regardless of how some other user has setted things?

I guess I'm requesting a new feature, a second argument, maybe, to filter autorepeat from system configuration.

I'll open a new request and link to this one...
