### ISSUE TITLE
Error initializing audio

### ISSUE THREAD

**Issue by ales-tsurko** [pure-data/pure-data#888]
macOS Catalina (10.15.2)

I hadn't been opening Pd for a while until today, when I considered to update it to the latest release (0.50-2). And now when I turn DSP on, I get:

```
error opening audio: Internal PortAudio error
```

The previous version I had (0.50-0) worked a few month ago. But I can't say precisely whether I'd updated to Catalina then or used Mojave.

Sorry if it's a duplicate, I didn't find the ticket for this issue. 

It's possibly related to #847.

**Comment by umlaeute** [comment]
does the audio work (despite the error)?

**Comment by AlesTsurko** [comment]
Here is how I fixed it:

Made some simple patch (i.e. with dac~), switched to Edit Mode, then turned DSP on. After that macOS asked whether I allow Pd to use microphone. After I allowed, everything worked.

So this is because of the Catalina's access control. 

To avoid this problem the "allow Pd to use mic" dialog should appear either on the first start of the program, or right after DSP turns on for the first time.

Steps to reproduce (macOS Catalina):

1. Install new version of Pd for the first time
2. Run the program
3. Turn DSP on

I also had this problem when:

4. Create a patch (osc~ 440 -> dac~)
5. Turn DSP off/on

It asked to allow to use microphone, when I:

6. Switched to edit mode
7. Turned DSP off/on

**Comment by AlesTsurko** [comment]
For some reason it stopped to work again. Described previously workaround doesn't help anymore. I get:

```
error opening audio: Internal PortAudio error
```

while Pd is in the list in Security & Privacy settings and it's allowed to use microphone.

**Comment by AlesTsurko** [comment]
And here is what I get when I run it in terminal:

```
||PaMacCore (AUHAL)|| Failed to open AUHAL component.||PaMacCore (AUHAL)|| Error on line 1263: err='-50', msg=Unknown Error
||PaMacCore (AUHAL)|| OpenStream @ 44100 returned: -9986: Internal PortAudio error
||PaMacCore (AUHAL)|| Failed to open AUHAL component.||PaMacCore (AUHAL)|| Error on line 1263: err='-50', msg=Unknown Error
||PaMacCore (AUHAL)|| OpenStream @ 44100 returned: -9986: Internal PortAudio error
```

The same happens in Audacity under Catalina: https://forum.audacityteam.org/viewtopic.php?t=107326

So it looks like it's related to PortAudio under Catalina. I've tried to compile Pd with:
- the version of PortAudio, which is on the master branch;
- using `update.sh` script to compile with the latest version;
- using the homebrew's version and `./configure --without-local-portaudio`.

With any of these versions I had the described errors.

**Comment by gorborukov** [comment]
> For some reason it stopped to work again. Described previously workaround doesn't help anymore. I get:
> 
> ```
> error opening audio: Internal PortAudio error
> ```
> 
> while Pd is in the list in Security & Privacy settings and it's allowed to use microphone.

Check macOS for unvalidated AudioUnit plugins, after removing unvalidated plugins PortAudio should work. At least in my case it helped.

**Comment by ales-tsurko** [comment]
@gorborukov Thanks! I cleaned up my mac from AU and VST plugins, which caused any errors in the Logic Pro X plugin manager. Still doesn't work... How did you find the unvalidated plugins?

**Comment by gorborukov** [comment]
> @gorborukov Thanks! I cleaned up my mac from AU and VST plugins, which caused any errors in the Logic Pro X plugin manager. Still doesn't work... How did you find the unvalidated plugins?

I had two unsigned self made plugins that did not pass validation, after plugins removal 'Internal PortAudio' error disappeared from Pd. I checked the validation through Logic Pro X -> Preferences -> Plug-In Manager -> Compatibility column. Unfortunately you probably have another case but make sure you don't have suspicious AU's from **both** library directories (user and drive): ~/Library/Audio/Plug-Ins/Components and /Library/Audio/Plug-Ins/Components.

**Comment by ales-tsurko** [comment]
OK. I just removed all the plugins from the home/user folder and it worked! Thanks! They also were the plugins I wrote myself. Apple possibly changed something related to AU validation.

**Comment by umlaeute** [comment]
so can we actually close this?
(it seems that the conclusion is that the problem is due to unrelated 3rd-party binaries and apple's security doctrine)

alternatively: does the problem get fixed with #1145?

**Comment by ales-tsurko** [comment]
Thanks everyone!
